Add files via upload
UV1L/Robots pull request #5
Opened 2020-05-27 11:39 UTC by UV1L

2020-05-27 11:42 UTC, UV1L commented
@shaykemelov вроде сейчас все поправил

2020-06-02 23:20 UTC, shaykemelov requested changes
tofix

2020-06-02 23:20 UTC, shaykemelov commented on robots/src/StateLogic/MemorableFrame.java
> +abstract public class MemorableFrame extends JInternalFrame {
Misordered modifires - нужно соблюдать convetion

`abstract public` -> `public abstract class`

2020-06-02 23:20 UTC, shaykemelov commented on robots/src/StateLogic/MemorableFrame.java
> +        var position = new Pair(getWidth(), getHeight());
для чего в `Pair` добавил дженерики, если не используешь их?

2020-06-02 23:20 UTC, shaykemelov commented on robots/src/StateLogic/Pair.java
> + * Просто тапл чтобы не хранить координаты поотдельности
Только координаты? А чего класс тогда используется для `width` и `height`? Не надо врать в `Java Docs`

2020-06-02 23:20 UTC, shaykemelov commented on robots/src/StateLogic/SaveNLoad.java
> +            FileWriter file = new FileWriter("states.txt");
используй `try with resources`, тогда не нужно будет руками ресурсы закрывать

2020-06-02 23:20 UTC, shaykemelov commented on robots/src/StateLogic/SaveNLoad.java
> +    public void saveStates(HashMap<String, State> allStates) {
Зачем завязываешься на реализации контейнера?

`HashMap<String, State>` -> `Map<String, State>`

2020-06-02 23:20 UTC, shaykemelov commented on robots/src/StateLogic/SaveNLoad.java
> +
зачем пустая строка?

2020-06-02 23:20 UTC, shaykemelov commented on robots/src/StateLogic/SaveNLoad.java
> +            FileWriter file = new FileWriter("states.txt");
`"states.txt"` используется в разных местах. можно вынести в константу и дать соответствующее имя.

2020-06-02 23:20 UTC, shaykemelov commented on robots/src/StateLogic/SaveNLoad.java
> +    public ArrayList<String> loadStates() {
Завязка на реализации списка

2020-06-02 23:20 UTC, shaykemelov commented on robots/src/StateLogic/SaveNLoad.java
> +            FileReader allStates = new FileReader("states.txt");
`try with resources`

2020-06-02 23:20 UTC, shaykemelov commented on robots/src/StateLogic/SaveNLoad.java
> +
пустая строка

2020-06-02 23:20 UTC, shaykemelov commented on robots/src/StateLogic/SaveNLoad.java
> +        catch (IOException ignored) {
вообще съедать ошибки - плохой тон. их обычно логируют. хотя бы стектрейс распечатай

2020-06-02 23:20 UTC, shaykemelov commented on robots/src/StateLogic/SaveNLoad.java
> +        catch (IOException ignored) {
не съедай ошибки - в продакшене аукнется

2020-06-02 23:20 UTC, shaykemelov commented on robots/src/StateLogic/SaveNLoad.java
> +
пустые строки

2020-06-02 23:20 UTC, shaykemelov commented on robots/src/StateLogic/State.java
> +
пустая строка

2020-06-02 23:20 UTC, shaykemelov commented on robots/src/StateLogic/State.java
> +    private final Pair<Integer, Integer> coordinates;
`position` вот никак не говорит мне о том, что это `width` и `height`

2020-06-02 23:20 UTC, shaykemelov commented on robots/src/gui/IMenuEvent.java
> +}
Вроде как интерфейс `Runnable` вполне справляется с этой задачей

2020-06-02 23:20 UTC, shaykemelov commented on robots/src/gui/LogWindow.java
> + */
такие джавадоки не годятся. в описании должно быть написано для чего этот класс предназначен, как им пользоваться, как не надо и тд.

2020-06-02 23:20 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
> +
пустая строка

2020-06-02 23:20 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
> +    private final HashMap<String, State> states = new HashMap<>();
замени реализации на интерфейсы

2020-06-02 23:20 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
> +     */
такое тоже не годится. в описании к методу - пишут что он делает, что принимает и что возвращает, в каких случаях какие ошибки выбрасывает

2020-06-02 23:20 UTC, shaykemelov commented on robots/src/gui/MenuCreator.java
> +    JFrame frame;
`private final JFrame frame;`

2020-06-02 23:20 UTC, shaykemelov commented on states.txt
> +log 1046 1034 163 107 true true
этот файл исключить из коммита, он не нужен. это просто мусор

2020-06-04 13:43 UTC, UV1L commented
@shaykemelov

2020-06-04 17:56 UTC, shaykemelov requested changes
tofix

2020-06-04 17:56 UTC, shaykemelov commented on states.txt
> +log 1046 1034 163 107 true true
удали его и добавь в `.gitignore`, либо храни его где-нибудь вне проекта, это будет лучшим решением

2020-06-04 17:56 UTC, shaykemelov commented on robots/src/gui/IMenuEvent.java
> +}
теперь этот класс можно удалить

2020-06-06 16:47 UTC, shaykemelov approved these changes
lgtm

2020-06-06 16:48 UTC, merged